version: 2.1

executors:
  default:
    docker:
      - image: cimg/node:lts
    working_directory: ~/React-chat-realtime
    

jobs:
  job_build:
    executor: default
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Trigger build
          command: |
            npx expo build:android -t apk
            ls -la

workflows:
  build_app:
    jobs:
      - job_build
          

